FROM postgres:12.5

ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres

COPY ./db /app
COPY ./db/init /docker-entrypoint-initdb.d
RUN chown -R postgres /app

USER postgres

EXPOSE 5432
